import { neon, type NeonQueryFunction } from "@neondatabase/serverless";

let sql: NeonQueryFunction<false, false> | null = null;
let migration: Promise<void> | null = null;

export function hasNeonDatabase() {
  return Boolean(process.env.DATABASE_URL);
}

export function getNeonSql() {
  if (sql) return sql;
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is not configured");
  sql = neon(connectionString);
  return sql;
}

export async function ensureNeonSchema() {
  if (!migration) {
    migration = migrate().catch((error) => {
      migration = null;
      throw error;
    });
  }
  await migration;
}

async function migrate() {
  const db = getNeonSql();
  await db`
    CREATE TABLE IF NOT EXISTS draw_results (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      issue TEXT NOT NULL UNIQUE,
      num1 SMALLINT NOT NULL CHECK(num1 BETWEEN 0 AND 9),
      num2 SMALLINT NOT NULL CHECK(num2 BETWEEN 0 AND 9),
      num3 SMALLINT NOT NULL CHECK(num3 BETWEEN 0 AND 9),
      sum SMALLINT NOT NULL CHECK(sum BETWEEN 0 AND 27),
      big_small TEXT NOT NULL,
      odd_even TEXT NOT NULL,
      pattern TEXT NOT NULL,
      open_time TIMESTAMPTZ,
      source TEXT NOT NULL DEFAULT 'jnd',
      raw_data JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
  await db`CREATE INDEX IF NOT EXISTS draw_results_issue_desc ON draw_results ((issue::BIGINT) DESC)`;
  await db`
    CREATE TABLE IF NOT EXISTS prediction_records (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      target_issue TEXT NOT NULL UNIQUE,
      based_on_issue TEXT NOT NULL,
      model_version TEXT NOT NULL DEFAULT 'v0.1',
      recommended_sum SMALLINT NOT NULL CHECK(recommended_sum BETWEEN 0 AND 27),
      top3 JSONB NOT NULL,
      top5 JSONB NOT NULL,
      score SMALLINT NOT NULL,
      confidence SMALLINT NOT NULL,
      confidence_label TEXT NOT NULL,
      risk_level TEXT NOT NULL,
      sample_size INTEGER NOT NULL,
      weights JSONB NOT NULL,
      probability_distribution JSONB NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      actual_sum SMALLINT CHECK(actual_sum BETWEEN 0 AND 27),
      is_hit BOOLEAN,
      generated_at TIMESTAMPTZ NOT NULL,
      settled_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
  await db`CREATE INDEX IF NOT EXISTS prediction_records_target_issue_desc ON prediction_records ((target_issue::BIGINT) DESC)`;
  await db`CREATE INDEX IF NOT EXISTS prediction_records_status ON prediction_records(status)`;

  // Compatibility migration for records written by the previous implementation.
  const legacy = await db`
    SELECT to_regclass('public.draw_records') IS NOT NULL AS draws,
           to_regclass('public.prediction_history') IS NOT NULL AS predictions
  ` as Array<{ draws: boolean; predictions: boolean }>;
  if (legacy[0]?.draws) {
    await db`
      INSERT INTO draw_results
        (issue,num1,num2,num3,sum,big_small,odd_even,pattern,open_time,source,raw_data,created_at,updated_at)
      SELECT issue,number_1,number_2,number_3,sum,
        CASE WHEN sum<=13 THEN '小' ELSE '大' END,
        CASE WHEN MOD(sum,2)=0 THEN '双' ELSE '单' END,
        pattern,open_time,'jnd',jsonb_build_object('rawOpenTime',raw_open_time),created_at,created_at
      FROM draw_records ON CONFLICT(issue) DO NOTHING`;
  }
  if (legacy[0]?.predictions) {
    await db`
      INSERT INTO prediction_records
        (target_issue,based_on_issue,model_version,recommended_sum,top3,top5,score,confidence,
         confidence_label,risk_level,sample_size,weights,probability_distribution,status,
         actual_sum,is_hit,generated_at,settled_at,created_at,updated_at)
      SELECT issue,(issue::BIGINT-1)::TEXT,'v0.1',recommended_sum,
        (SELECT COALESCE(jsonb_agg(point),'[]'::jsonb) FROM
          (SELECT point FROM jsonb_array_elements(distribution_json) point
           ORDER BY (point->>'probability')::numeric DESC LIMIT 3) x),
        (SELECT COALESCE(jsonb_agg(point),'[]'::jsonb) FROM
          (SELECT point FROM jsonb_array_elements(distribution_json) point
           ORDER BY (point->>'probability')::numeric DESC LIMIT 5) x),
        comprehensive_score,confidence_index,confidence_label,risk,sample_size,
        weights_json,distribution_json,
        CASE WHEN actual_sum IS NULL THEN 'pending' ELSE 'settled' END,
        actual_sum,hit,predicted_at,checked_at,predicted_at,COALESCE(checked_at,predicted_at)
      FROM prediction_history ON CONFLICT(target_issue) DO NOTHING`;
  }
}
